import type { TemplateRoutine } from "./routine";

export const templateRoutines = [
  {
    id: "commute",
    title: "출근",
    hint: "사원증, 충전기, 우산까지",
    prepFlowGroup: "now",
    categoryGroup: "daily",
    tags: ["회사", "사무실", "출근길", "첫 출근"],
    baseItems: [
      "휴대폰",
      "지갑/카드",
      "이어폰",
      "사원증",
      "노트북/충전기",
      "우산 확인",
      "텀블러",
    ],
  },
  {
    id: "outing",
    title: "외출",
    hint: "집 키, 카드, 보조배터리까지",
    prepFlowGroup: "now",
    categoryGroup: "daily",
    tags: ["약속", "나들이", "산책", "외출준비"],
    baseItems: [
      "휴대폰",
      "지갑/카드",
      "이어폰",
      "집 키",
      "보조배터리",
      "날씨 확인",
      "예약/약속 시간 확인",
    ],
  },
  {
    id: "workout",
    title: "운동",
    hint: "수건이랑 이어폰 챙겼나요?",
    prepFlowGroup: "now",
    categoryGroup: "health",
    tags: ["헬스", "필라테스", "러닝", "운동장"],
    baseItems: [
      "운동복",
      "운동화",
      "수건",
      "물병",
      "이어폰",
      "락커키/회원카드",
      "샤워용품",
    ],
  },
  {
    id: "rainy",
    title: "비 오는 날",
    hint: "우산만 챙기면 끝이 아닐 수도 있어요",
    prepFlowGroup: "todayTomorrow",
    categoryGroup: "daily",
    tags: ["비", "우산", "장마", "눈", "날씨"],
    baseItems: [
      "우산",
      "여분 양말",
      "방수 신발 확인",
      "가방 방수 커버",
      "교통 지연 여유시간",
    ],
  },
  {
    id: "hospital",
    title: "병원",
    hint: "신분증부터 복용 중인 약까지",
    prepFlowGroup: "todayTomorrow",
    categoryGroup: "health",
    tags: ["약국", "진료", "검진", "신분증", "예약"],
    baseItems: [
      "신분증",
      "예약 시간 확인",
      "복용 중인 약 이름",
      "증상 메모",
      "결제 수단",
      "보험/실손 관련 메모",
    ],
  },
  {
    id: "grocery",
    title: "퇴근길 장보기",
    hint: "저녁 재료와 생필품을 한 번 더",
    prepFlowGroup: "todayTomorrow",
    categoryGroup: "family",
    tags: ["마트", "장보기", "생필품", "저녁거리"],
    baseItems: [
      "우유/계란 등 기본 식재료",
      "오늘 저녁 재료",
      "휴지/세제 등 생활용품",
      "할인/쿠폰 확인",
      "무거운 품목 먼저 확인",
    ],
  },
  {
    id: "childSchool",
    title: "아이 등원/등교",
    hint: "물병, 알림장, 여벌옷까지",
    prepFlowGroup: "todayTomorrow",
    categoryGroup: "family",
    tags: ["어린이집", "유치원", "학교", "준비물"],
    baseItems: [
      "가방",
      "물통",
      "수저통/식기",
      "준비물",
      "알림장/앱 공지 확인",
      "여벌옷",
      "우산/외투",
    ],
  },
  {
    id: "businessTrip",
    title: "출장/외근",
    hint: "충전기와 발표자료, 나가기 전에 한 번 더",
    prepFlowGroup: "todayTomorrow",
    categoryGroup: "work",
    tags: ["미팅", "외근", "발표", "출장"],
    baseItems: [
      "노트북",
      "충전기",
      "신분증",
      "교통 티켓/예약 확인",
      "발표자료/문서",
      "명함",
      "결제 수단/법인카드",
      "세면도구",
    ],
  },
  {
    id: "golf",
    title: "골프",
    hint: "장갑, 볼마커, 티오프 시간까지",
    prepFlowGroup: "early",
    categoryGroup: "leisure",
    tags: ["라운딩", "스크린", "골프장", "필드"],
    baseItems: [
      "골프화",
      "장갑",
      "모자",
      "골프복/여벌 옷",
      "골프공/티",
      "볼마커",
      "거리측정기",
      "선크림",
      "예약/티오프 시간 확인",
    ],
  },
  {
    id: "camping",
    title: "캠핑",
    hint: "랜턴 배터리와 연료처럼 작은 걸 놓치지 않게",
    prepFlowGroup: "early",
    categoryGroup: "leisure",
    tags: ["글램핑", "차박", "야영", "캠프"],
    baseItems: [
      "텐트/타프",
      "침낭/매트",
      "랜턴/배터리",
      "버너/연료",
      "식재료/물",
      "세제/수세미/키친타월",
      "의자/테이블",
      "쓰레기봉투",
      "예약/입실 시간 확인",
    ],
  },
  {
    id: "domesticTravel",
    title: "국내여행",
    hint: "숙소, 교통편, 충전기까지",
    prepFlowGroup: "early",
    categoryGroup: "leisure",
    tags: ["여행", "국내", "호캉스", "숙소", "KTX", "렌터카"],
    baseItems: [
      "신분증",
      "지갑/카드",
      "휴대폰/충전기",
      "보조배터리",
      "세면도구",
      "여벌 옷",
      "상비약",
      "숙소/교통 예약 확인",
      "교통편/KTX/렌터카 예약 확인",
    ],
  },
  {
    id: "overseasTravel",
    title: "해외여행",
    hint: "여권, eSIM, 멀티어댑터까지",
    prepFlowGroup: "early",
    categoryGroup: "leisure",
    tags: ["여행", "해외", "공항", "여권", "환전", "eSIM"],
    baseItems: [
      "여권",
      "항공권/탑승 시간 확인",
      "지갑/카드",
      "현지 결제 수단/환전",
      "휴대폰/충전기",
      "보조배터리",
      "멀티어댑터",
      "eSIM/로밍 확인",
      "세면도구",
      "여벌 옷",
      "상비약",
      "숙소 예약 확인",
    ],
  },
  {
    id: "hiking",
    title: "등산",
    hint: "물, 간식, 바람막이까지",
    prepFlowGroup: "early",
    categoryGroup: "leisure",
    tags: ["산행", "트레킹", "등산화", "스틱", "물"],
    baseItems: [
      "등산화",
      "물",
      "간식",
      "모자/선크림",
      "바람막이/외투",
      "보조배터리",
      "등산 스틱, 선택",
      "손전등/헤드랜턴, 선택",
      "쓰레기봉투",
    ],
  },
] as const satisfies readonly TemplateRoutine[];

export function getTemplateRoutine(id: TemplateRoutine["id"]): TemplateRoutine {
  const routine = templateRoutines.find((template) => template.id === id);

  if (!routine) {
    throw new Error(`Unknown routine template: ${id}`);
  }

  return routine;
}
